// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const body: string;
export const aCustomcard: string;
export const contentblog: string;
export const contentblog2: string;
export const backgroundduty: string;
export const texture2: string;
export const textparagraph: string;
export const picmodal: string;
